/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ApiPublicOnipayRouteImport } from './routes/api/public/onipay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnipayRoute = ApiPublicOnipayRouteImport.update({
  id: '/api/public/onipay',
  path: '/api/public/onipay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/onipay': typeof ApiPublicOnipayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/onipay': typeof ApiPublicOnipayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/onipay': typeof ApiPublicOnipayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/produto/$id' | '/api/public/onipay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/produto/$id' | '/api/public/onipay'
  id: '__root__' | '/' | '/produto/$id' | '/api/public/onipay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicOnipayRoute: typeof ApiPublicOnipayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onipay': {
      id: '/api/public/onipay'
      path: '/api/public/onipay'
      fullPath: '/api/public/onipay'
      preLoaderRoute: typeof ApiPublicOnipayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicOnipayRoute: ApiPublicOnipayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
